### ISSUE TITLE
TS config + source maps

### ISSUE THREAD

**Issue by bodhi** [petester42/jest-preset-typescript-react-native#4]
Hi, we want to generate test coverage information, but this preset doesn't include `sourceMap` in the generated TS Config: https://github.com/petester42/jest-preset-typescript-react-native/blob/5494154d7aae701a1efed1a4903c1f42fb2a1bf2/preprocessor.js#L2-L8

and there's no way to add it in. This results in the coverage data being incorrect.

Would it be possible to read in options from `package.json` similar to how `ts-jest` works, or at least add `sourceMap` to the default config?

Thanks for the useful project too, by the way!

**Comment by pmairoldi** [comment]
I'll look into.

**Comment by pmairoldi** [comment]
If you could give me an example of the coverage being wrong like an example source file that would be great. I can't really reproduce the coverage being wrong.

**Comment by pmairoldi** [comment]
Actually never mind. I see what you mean.

**Comment by pmairoldi** [comment]
I've found a solution but your `tsconfig.json` file will need to have `inlineSourceMap` set to true. The solution you proposed to adding `sourceMap` to the preprocessor config won't work since the preprocessor is only for the test files, not the source files. If there is a way to read the source file imports and link the proper source files I'm all ears but for now I have no solution besides inlining the `sourceMaps`

**Comment by bodhi** [comment]
Thanks @petester42 for looking into it so quickly.

> I've found a solution but your tsconfig.json file will need to have `inlineSourceMap` set to true.

I had no idea that option even existed 😸 

That could work. If the RN bundler doesn't strip out the source map for production builds, we could get by with having a separate `tsconfig.json` for running the test suite. Oh, is that possible?

If not, including the source-maps isn't such a disaster since bundle size isn't such an important constraint on native mobile apps.

**Comment by pmairoldi** [comment]
Seems like other projects like ts-jest propose to inline source maps. You can set different tsconfig when using tsc. All the docs can be found [here](http://www.typescriptlang.org/docs/handbook/tsconfig-json.html) but basically its `tsc --project otherTSConfig.json`
